# Generated by Django 5.0.2 on 2024-03-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_address_details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
