# Generated by Django 5.0.4 on 2024-06-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
