# Generated by Django 5.0.4 on 2024-06-21 02:29

import django.core.validators
import furbar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(blank=True, default=furbar.models.generate_coupon_value, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('discount_amount', models.SmallIntegerField()),
                ('is_persent_discount', models.BooleanField(default=True)),
                ('expiration_date', models.DateField()),
                ('max_usage_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('usage_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
