# Generated by Django 5.0.2 on 2024-03-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
