# Generated by Django 5.0.4 on 2024-06-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0002_product_rating_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
