# Generated by Django 5.0.4 on 2024-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
