# Generated by Django 5.0.2 on 2024-03-11 03:24

import furbar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0002_alter_user_additional_address_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', furbar.models.CustomUserManager()),
            ],
        ),
    ]
