# Generated by Django 5.0.4 on 2024-06-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0003_article_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='vote',
        ),
    ]
