# Generated by Django 5.0.2 on 2024-03-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0004_remove_product_discount_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wish_list',
            new_name='wishlist',
        ),
    ]
