# Generated by Django 5.0.4 on 2024-06-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0004_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseorder',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online')], default='online', max_length=30),
        ),
        migrations.AddField(
            model_name='takeawayorder',
            name='payment_type',
            field=models.CharField(choices=[('online', 'online'), ('on_receipt', 'on_receipt')], default='online', max_length=30),
        ),
    ]
