# Generated by Django 5.0.4 on 2024-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0005_alter_article_rating_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vote_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='vote_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
