# Generated by Django 5.0.4 on 2024-06-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0005_houseorder_payment_type_takeawayorder_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseorder',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Оплата онлайн')], default='online', max_length=30),
        ),
        migrations.AlterField(
            model_name='takeawayorder',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Оплата онлайн'), ('on_receipt', 'Оплата при получении')], default='online', max_length=30),
        ),
    ]
