# Generated by Django 5.0.4 on 2024-06-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0006_alter_houseorder_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(default='1', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='street_name',
            field=models.CharField(default='1', max_length=120),
            preserve_default=False,
        ),
    ]
