# Generated by Django 5.0.4 on 2024-06-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0007_alter_categoryimage_category_alter_userimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
