# Generated by Django 5.0.4 on 2024-06-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0007_remove_warehouse_name_warehouse_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='street_name',
            new_name='additional_address',
        ),
    ]
