# Generated by Django 5.0.4 on 2024-06-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furbar', '0008_alter_article_rating_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='furbar.product')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='buy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='furbar.buy'),
        ),
    ]
